*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZDLVWRICK_002...................................*
FORM GET_DATA_ZDLVWRICK_002.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZDLRICK_005 WHERE
(VIM_WHERETAB) .
    CLEAR ZDLVWRICK_002 .
ZDLVWRICK_002-MANDT =
ZDLRICK_005-MANDT .
ZDLVWRICK_002-EQUIPE =
ZDLRICK_005-EQUIPE .
ZDLVWRICK_002-USUARIO =
ZDLRICK_005-USUARIO .
<VIM_TOTAL_STRUC> = ZDLVWRICK_002.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZDLVWRICK_002 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZDLVWRICK_002.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZDLVWRICK_002-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZDLRICK_005 WHERE
  EQUIPE = ZDLVWRICK_002-EQUIPE AND
  USUARIO = ZDLVWRICK_002-USUARIO .
    IF SY-SUBRC = 0.
    DELETE ZDLRICK_005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZDLRICK_005 WHERE
  EQUIPE = ZDLVWRICK_002-EQUIPE AND
  USUARIO = ZDLVWRICK_002-USUARIO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZDLRICK_005.
    ENDIF.
ZDLRICK_005-MANDT =
ZDLVWRICK_002-MANDT .
ZDLRICK_005-EQUIPE =
ZDLVWRICK_002-EQUIPE .
ZDLRICK_005-USUARIO =
ZDLVWRICK_002-USUARIO .
    IF SY-SUBRC = 0.
    UPDATE ZDLRICK_005 ##WARN_OK.
    ELSE.
    INSERT ZDLRICK_005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZDLVWRICK_002-UPD_FLAG,
STATUS_ZDLVWRICK_002-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZDLVWRICK_002.
  SELECT SINGLE * FROM ZDLRICK_005 WHERE
EQUIPE = ZDLVWRICK_002-EQUIPE AND
USUARIO = ZDLVWRICK_002-USUARIO .
ZDLVWRICK_002-MANDT =
ZDLRICK_005-MANDT .
ZDLVWRICK_002-EQUIPE =
ZDLRICK_005-EQUIPE .
ZDLVWRICK_002-USUARIO =
ZDLRICK_005-USUARIO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZDLVWRICK_002 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZDLVWRICK_002-EQUIPE TO
ZDLRICK_005-EQUIPE .
MOVE ZDLVWRICK_002-USUARIO TO
ZDLRICK_005-USUARIO .
MOVE ZDLVWRICK_002-MANDT TO
ZDLRICK_005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZDLRICK_005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZDLRICK_005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZDLRICK_005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
