PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDLRICK_003 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDLRICK_003-ID .
    FIELD ZDLRICK_003-TITULO .
    FIELD ZDLRICK_003-DESCRICAO .
    FIELD ZDLRICK_003-MODULO .
    FIELD ZDLRICK_003-SETOR .
    FIELD ZDLRICK_003-EQUIPE .
    FIELD ZDLRICK_003-RESPONSAVEL .
    FIELD ZDLRICK_003-DATA_INICIO .
    FIELD ZDLRICK_003-DATA_FIM_ESPERADA .
    FIELD ZDLRICK_003-DATA_FIM_REAL .
    FIELD ZDLRICK_003-CRIADO_POR .
    FIELD ZDLRICK_003-CRIADO_EM .
    FIELD ZDLRICK_003-MODIFICADO_POR .
    FIELD ZDLRICK_003-MODIFICADO_EM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDLRICK_003-ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
