PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDLRICK_006 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDLRICK_006-ID .
    FIELD ZDLRICK_006-DESCRICAO .
    FIELD ZDLRICK_006-MODIFICAR_PROJETO .
    FIELD ZDLRICK_006-CRIAR_TICKET .
    FIELD ZDLRICK_006-MODIFICAR_TICKET .
    FIELD ZDLRICK_006-MOVER_TICKET .
    FIELD ZDLRICK_006-COMENTAR_TICKET .
    FIELD ZDLRICK_006-CRIAR_ARQUIVO .
    FIELD ZDLRICK_006-DELETAR_ARQUIVO .
    FIELD ZDLRICK_006-APONTAR_HORAS .
    FIELD ZDLRICK_006-APROVAR_HORAS .
    FIELD ZDLRICK_006-CRIADO_POR .
    FIELD ZDLRICK_006-CRIADO_EM .
    FIELD ZDLRICK_006-MODIFICADO_POR .
    FIELD ZDLRICK_006-MODIFICADO_EM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDLRICK_006-ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
